name: robo
channels:
  - pytorch
  - nvidia
  - fair-robotics
  - conda-forge
  - defaults
dependencies:
    # Build dependencies
    - assimp=5.0.1=hdca8b6f_4
    - cmake
    - cpuonly
    - doxygen
    - eigen=3.3.9
    - grpc-cpp=1.41.1
    - hpp-fcl=1.6.0
    - libprotobuf=3.18.1
    - mkl-include ==2022.0.1
    - openmpi=2.1.2
    - pinocchio ==2.5.2
    - poco ==1.9.0 # needed by libfranka
    - python ==3.9
    - pytorch=2.0.1
    - torchvision
    - urdfdom=2.3.3=hc9558a2_0
    - urdfdom_headers=1.0.5=hc9558a2_2
    - yaml-cpp ==0.6.3

    # Run dependencies
    - asv
    - black
    - boost ==1.72.0
    - boost-cpp ==1.72.0
    - breathe
    - dash
    - grpcio ==1.46.0
    - mujoco
    - hydra-core ==1.0.6
    - importlib-resources ==5.7.1
    - myst-parser
    - numpy
    - pandas
    - plotly
    - pip
    - protobuf
    - pybullet ==3.17
    - pymodbus ==2.5.3
    - pyserial
    - pytest
    - pytest-benchmark=4.0.0
    - scipy
    - spdlog=1.10.0=h924138e_0
    - sphinx
    - sphinx-copybutton
    - sphinx-book-theme
    - tqdm
